:PROPERTIES:
:ID:       d30cf069-0ff3-4544-83e3-6fc450f0ed75
:END:
#+title:OPTIMAL ERROR ESTIMATES OF A LINEARIZED BACKWARD EULER FEM FOR THE LANDAU–LIFSHITZ EQUATION"
#+FILETAGS: reading
- tags :: 
- sources :: "C:\Users\Liyaoda\Nutstore\1\zotero\gaoOptimalErrorEstimates2014.pdf"
* Author
Huadong Gao
* Equation

* Main aim
Construct a fully discrete linearized scheme for LL equation and give an almost unconditionally error estimate for it.
* Background and Problems
In the last twenty years, mathematical analysis and numerical simulation of LL equation have been done.

However, we should obey some strong restrictive step conditions in order to obtain the convergence estimate for LL equations.

The greatest problem is the strong nonlinearities and coupling of the system.
* Methods
** Time and Spatial
Time direction: Linearized Backward Euler

Spatial direction: FEM
** Thinks
Maybe we can change the time discretation method.
** Highlight
The author propose a new linearization to the nonlinear hyromagnetic term $\gamma m\times \Delta m$.

The linearization is based on a linear treatment of the weak form of the nonlinear term by
\begin{equation*}
\gamma(m\times\Delta m,\phi)=-\gamma(\nabla m\times\nabla m,\nabla\phi)-\gamma(m\times\nabla m,\nabla\phi)\approx-\gamma(m_h^j\times\nabla m_h^{j+1},\nabla\phi)
\end{equation*}

It requires less computations to generate the stiffness matrix at each time step.
*** Trick
Temporal-spatial splitting method.
